name: "PR Summary Generator"
description: "Generates a summary for pull requests using LLM"

branding:
    icon: message-square
    color: blue

inputs:
    github-token:
        description: "GitHub token for authentication"
        required: true
    ollama-url:
        description: "URL for Ollama service"
        required: true
    model-name:
        description: "Name of the Ollama model to use"
        required: false
        default: "deepseek-r1:8b"

runs:
    using: "composite"
    steps:
        - name: "Checkout Repository"
          uses: actions/checkout@v4

        - name: "Set up Python"
          uses: actions/setup-python@v4
          with:
              python-version: "3.11"

        - name: "Install dependencies"
          shell: bash
          working-directory: ${{ github.action_path }}
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: "Generate PR Summary"
          shell: bash
          working-directory: ${{ github.action_path }}
          env:
              GITHUB_TOKEN: ${{ inputs.github-token }}
              OLLAMA_URL: ${{ inputs.ollama-url }}
              REPO_NAME: ${{ github.repository }}
              PR_NUMBER: ${{ github.event.pull_request.number }}
              MODEL_NAME: ${{ inputs.model-name }}
          run: |
              python main.py
              echo "PR summary generated for PR #${{ github.event.pull_request.number }} in ${github.repository}"
