name: "PR Summary Generator"
description: "Generates a summary for pull requests using LLM"

branding:
    icon: message-square
    color: blue

inputs:
    github-token:
        description: "GitHub token for authentication"
        required: true
    ollama-url:
        description: "URL for Ollama service"
        required: true
    model-name:
        description: "Name of the Ollama model to use"
        required: false
        default: "deepseek-r1:8b"

runs:
    using: "python"
    main: "main.py"
