name: "Build and Push Docker Image"
description: "Builds and pushes a Docker image to GitHub Container Registry"

branding:
    icon: check-circle
    color: green

inputs:
    dockerfile:
        description: "Path to the Dockerfile"
        required: true
    github-token:
        description: "GitHub token for authentication"
        required: true
    image-name:
        description: "Name of the Docker image"
        required: false
        default: ${{ github.repository }}

outputs:
    image:
        description: "The full image name that was built and pushed"

runs:
    using: "node16"
    main: "index.js"
