name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Set up Docker tag
        run: echo "IMAGE_TAG=morbo:v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG .

