name: PR Summary Generator

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    generate-summary:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: List vars
              run: |
                  echo "GITHUB_REF: ${{ github.ref }}"
                  echo "GITHUB_REPO: ${{ github.repository }}"
                  echo "GITHUB_EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}"
                  echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

            # - name: Install dependencies
            #   run: |
            #       pip install -r requirements.txt

            # - name: Generate PR Summary
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: python main.py ${{github.repository}}/${{github.base_ref}} ${{ github.event.pull_request.number }}
